package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

func runReport(args []string) error {
	fs := flag.NewFlagSet("report", flag.ExitOnError)
	localPath := fs.String("local", "", "local-leg results JSON (from transcribe --label local)")
	openaiPath := fs.String("openai", "", "openai-leg results JSON (from transcribe --label openai)")
	out := fs.String("out", "", "output markdown path")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *localPath == "" || *openaiPath == "" || *out == "" {
		return fmt.Errorf("--local, --openai, and --out are required")
	}

	local, err := loadResults(*localPath)
	if err != nil {
		return fmt.Errorf("load local results: %w", err)
	}
	openai, err := loadResults(*openaiPath)
	if err != nil {
		return fmt.Errorf("load openai results: %w", err)
	}

	openaiByFile := map[string]fileResult{}
	for _, r := range openai {
		openaiByFile[r.Filename] = r
	}

	var filenames []string
	localByFile := map[string]fileResult{}
	for _, r := range local {
		localByFile[r.Filename] = r
		filenames = append(filenames, r.Filename)
	}
	sort.Strings(filenames)

	var b strings.Builder
	b.WriteString("# Whisper transcription spot-check — review\n\n")
	b.WriteString("Generated by `cmd/whisper_spotcheck`. This artifact does NOT contain an accuracy ")
	b.WriteString("judgment — Claude Code cannot hear the audio. Fill in the **Manual accuracy rating** ")
	b.WriteString("column by ear, then this feeds the decision in `whisper_spotcheck_review.md`.\n\n")
	b.WriteString("**How to rate:** use whatever scale is most useful to you (e.g. usable/unusable, ")
	b.WriteString("or a 1-5 scale, or a word-error estimate) — just be consistent, and note which ")
	b.WriteString("scale you used so the aggregate analysis step interprets it correctly.\n\n")
	b.WriteString("**Confidence columns** are Whisper's own segment-level `avg_logprob`/`no_speech_prob` ")
	b.WriteString("(a log-probability — closer to 0 is more confident, more negative is less), the signal ")
	b.WriteString("proposal §5's escalation trigger is actually about. Word-level probabilities were tried ")
	b.WriteString("first but dropped: requesting them from OpenAI's real API suppresses its segment data ")
	b.WriteString("entirely and returns only placeholder (always-0) word probabilities — see ")
	b.WriteString("`whisper_spotcheck_review.md` for that finding.\n\n")

	for _, name := range filenames {
		l := localByFile[name]
		o, haveOpenAI := openaiByFile[name]

		b.WriteString("---\n\n")
		fmt.Fprintf(&b, "## %s\n\n", name)

		b.WriteString("**Local (Speaches / faster-whisper-large-v3):**\n\n")
		writeLegBody(&b, l)

		b.WriteString("\n**OpenAI Whisper:**\n\n")
		if haveOpenAI {
			writeLegBody(&b, o)
		} else {
			b.WriteString("_(no OpenAI result for this file)_\n\n")
		}

		b.WriteString("\n| Manual accuracy rating | Code-switch boundary error? | Notes |\n")
		b.WriteString("|---|---|---|\n")
		b.WriteString("| | | |\n\n")
	}

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}

	fmt.Printf("wrote %s (%d files)\n", *out, len(filenames))
	return nil
}

func writeLegBody(b *strings.Builder, r fileResult) {
	if r.Error != "" {
		fmt.Fprintf(b, "**ERROR:** `%s`\n\n", r.Error)
		return
	}
	if r.Response == nil {
		b.WriteString("_(no result)_\n\n")
		return
	}

	fmt.Fprintf(b, "> %s\n\n", strings.TrimSpace(r.Response.Text))
	fmt.Fprintf(b, "- language detected: `%s`, duration: %.1fs, request time: %dms\n", r.Response.Language, r.Response.Duration, r.RequestMS)

	if r.Metrics != nil {
		fmt.Fprintf(b, "- mean segment avg_logprob: %.3f, mean no_speech_prob: %.3f (n=%d segments)\n",
			r.Metrics.MeanSegmentAvgLogprob, r.Metrics.MeanNoSpeechProb, len(r.Response.Segments))
	}
	b.WriteString("\n")
}

func loadResults(path string) ([]fileResult, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var results []fileResult
	if err := json.Unmarshal(data, &results); err != nil {
		return nil, err
	}
	return results, nil
}
