package main

import (
	"fmt"
	"math/rand"
	"os"
	"sort"
	"strings"
)

// writeSample builds the manual-review artifact: a random (stratified by
// source file, when more than one is given) sample of extracted edges
// with their source conversation context, and a blank annotation table —
// same style as cmd/whisper_spotcheck's report.go (one section per item,
// a blank table row for hand-filling, no accuracy judgment baked in).
func writeSample(path string, runs []RunResult, size int, seed int64) error {
	items := flattenOutcomes(runs)

	sampled := stratifiedSample(items, size, seed)

	var b strings.Builder
	b.WriteString("# Phase 0 validation dry-run — manual accuracy sample\n\n")
	fmt.Fprintf(&b, "Generated by `cmd/phase0_dryrun`, seed=%d. This artifact does NOT contain an accuracy judgment ", seed)
	b.WriteString("— Claude Code cannot verify these facts against Marco's real conversations or life. Fill in the ")
	b.WriteString("**Correct?** column by hand, then this feeds the error-rate computation in `summary.md`'s ")
	b.WriteString("decision inputs.\n\n")
	b.WriteString("**How to judge \"correct\"**: use whatever definition is actually useful to you — e.g. strict ")
	b.WriteString("(subject/predicate/object all exactly right) vs. lenient (the gist is right even if phrasing is ")
	b.WriteString("off), or a finer scale than y/n if that's more useful. Just be consistent, and note which ")
	b.WriteString("definition you used somewhere in this file so a later read of the annotations interprets it ")
	b.WriteString("correctly — same caveat cmd/whisper_spotcheck's report asked for and for the same reason: this ")
	b.WriteString("tooling has no way to guess what \"correct\" should mean for your data.\n\n")

	fmt.Fprintf(&b, "Sample size: %d of %d total extracted triples across %d conversation(s).\n\n", len(sampled), len(items), len(runs))

	if len(items) == 0 {
		b.WriteString("_(no extracted triples to sample — nothing to review)_\n")
		return os.WriteFile(path, []byte(b.String()), 0o644)
	}

	for i, it := range sampled {
		b.WriteString("---\n\n")
		fmt.Fprintf(&b, "## %d. %s\n\n", i+1, edgeDescription(it.Outcome))
		fmt.Fprintf(&b, "_Source: %s, window %d, action=%s_\n\n", it.SourceFile, it.WindowIndex, it.Outcome.Action)
		b.WriteString("**Source conversation:**\n\n")
		b.WriteString(windowContext(it.WindowMessages))
		b.WriteString("\n| Correct? (y/n) | Note |\n|---|---|\n| | |\n\n")
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// stratifiedSample picks up to size items from all, spreading the
// selection roughly evenly across each distinct SourceFile (conversation)
// present — so one especially chatty conversation can't crowd out the
// others in the sample — then randomly selects within each group.
// Falls back to plain random sampling when there's only one source file,
// which is the common case (one export == one conversation, per
// ImportWhatsApp's own scope). Deterministic given the same seed, so a
// sample can be regenerated identically (e.g. after fixing a report
// formatting bug) without reshuffling which edges got picked.
func stratifiedSample(all []sampleItem, size int, seed int64) []sampleItem {
	if size >= len(all) {
		sorted := append([]sampleItem(nil), all...)
		r := rand.New(rand.NewSource(seed))
		r.Shuffle(len(sorted), func(i, j int) { sorted[i], sorted[j] = sorted[j], sorted[i] })
		return sorted
	}

	byFile := map[string][]sampleItem{}
	var files []string
	for _, it := range all {
		if _, ok := byFile[it.SourceFile]; !ok {
			files = append(files, it.SourceFile)
		}
		byFile[it.SourceFile] = append(byFile[it.SourceFile], it)
	}
	sort.Strings(files) // deterministic file iteration order given a fixed seed

	r := rand.New(rand.NewSource(seed))
	for _, f := range files {
		r.Shuffle(len(byFile[f]), func(i, j int) { byFile[f][i], byFile[f][j] = byFile[f][j], byFile[f][i] })
	}

	var sampled []sampleItem
	perFile := (size + len(files) - 1) / len(files)
	for _, f := range files {
		group := byFile[f]
		n := perFile
		if n > len(group) {
			n = len(group)
		}
		sampled = append(sampled, group[:n]...)
	}

	if len(sampled) > size {
		r.Shuffle(len(sampled), func(i, j int) { sampled[i], sampled[j] = sampled[j], sampled[i] })
		sampled = sampled[:size]
	}

	return sampled
}
