package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/marcoantonios1/Pegasus/internal/api"
	"github.com/marcoantonios1/Pegasus/internal/extraction"
)

const outlierCount = 10 // how many lowest/highest-confidence triples to list explicitly

func writeSummary(path string, runs []RunResult, totalMonths float64) error {
	var b strings.Builder

	b.WriteString("# Phase 0 validation dry-run — summary\n\n")
	b.WriteString("Generated by `cmd/phase0_dryrun`. This report does NOT contain an accuracy judgment or a go/no-go ")
	b.WriteString("recommendation — Claude Code cannot judge extraction quality against Marco's real conversations, ")
	b.WriteString("and building that judgment in here would be exactly the mistake this issue's own scope explicitly ")
	b.WriteString("rules out. What follows are the three inputs the roadmap's Phase 0 decision needs, reported side ")
	b.WriteString("by side, decided by Marco:\n\n")
	b.WriteString("1. **Extraction error rate** — from `sample.md`, once filled in by hand.\n")
	b.WriteString("2. **Cost extrapolation** — below, from Costguard's own real usage data for this run.\n")
	b.WriteString("3. **Failure clusters** — below: confidence outliers, triage-flagged-but-empty windows, and ")
	b.WriteString("closed-vocabulary rejections. Whether these point to a fixable prompt/vocabulary issue or an ")
	b.WriteString("acceptable noise floor is a judgment call this report does not make.\n\n")

	writePipelineMetrics(&b, runs)
	writeCostAndTiming(&b, runs, totalMonths)
	writeFailureClusters(&b, runs)

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writePipelineMetrics(b *strings.Builder, runs []RunResult) {
	b.WriteString("---\n\n## Pipeline metrics\n\n")

	var messagesParsed, textExtractable, windowsTotal, windowsCandidate int
	var created, reinforced, corrected, skipped int

	for _, r := range runs {
		if r.Import == nil {
			continue
		}
		messagesParsed += r.Import.MessagesParsed
		textExtractable += r.Import.MessagesTextExtractable
		windowsTotal += len(r.Import.Windows)
		for _, w := range r.Import.Windows {
			if w.IsCandidate {
				windowsCandidate++
			}
			for _, o := range w.Outcomes {
				switch o.Action {
				case api.TripleActionCreated:
					created++
				case api.TripleActionReinforced:
					reinforced++
				case api.TripleActionCorrected:
					corrected++
				case api.TripleActionSkippedNoCorrectionTarget:
					skipped++
				}
			}
		}
	}

	candidateRate := 0.0
	if windowsTotal > 0 {
		candidateRate = 100 * float64(windowsCandidate) / float64(windowsTotal)
	}

	fmt.Fprintf(b, "- Conversations (input files): %d\n", len(runs))
	fmt.Fprintf(b, "- Messages parsed from export(s): %d\n", messagesParsed)
	fmt.Fprintf(b, "- Text messages (extractable — voice/image/video are stored but never reach triage/extraction, see below): %d\n", textExtractable)
	fmt.Fprintf(b, "- Windows (batches of up to %d messages sent to triage together): %d\n", extraction.DefaultHistoricalWindowSize, windowsTotal)
	fmt.Fprintf(b, "- Windows triage flagged as candidates: %d (%.1f%%)\n", windowsCandidate, candidateRate)
	b.WriteString("\n  **On this rate vs. §5's 10-20% estimate**: this is a WINDOW-level rate, not a message-level ")
	b.WriteString("one — triage here runs once per window (a batched call covering several messages at once, per ")
	b.WriteString("§5's own cost-discipline note for historical import), not once per message the way live triage ")
	b.WriteString("does. A window is all-or-nothing: if even one message in it looks worth extracting, the whole ")
	b.WriteString("window is flagged. That structurally pushes this number ABOVE what a true per-message rate would ")
	b.WriteString("show — comparing it directly to §5's 10-20% estimate is comparing two different units. Useful as ")
	b.WriteString("a first data point, not a clean apples-to-apples check.\n\n")

	fmt.Fprintf(b, "- Extraction (Pass 2) calls: %d (one per candidate window)\n", windowsCandidate)
	fmt.Fprintf(b, "- Edges created (new facts): %d\n", created)
	fmt.Fprintf(b, "- Edges reinforced (same fact seen again): %d\n", reinforced)
	fmt.Fprintf(b, "- Edges corrected (via CorrectMemory, IsCorrection triples): %d\n", corrected)
	fmt.Fprintf(b, "- Triples skipped (is_correction=true naming nothing to correct): %d\n", skipped)
	fmt.Fprintf(b, "- Total edges touched: %d\n\n", created+reinforced+corrected)
}

func writeCostAndTiming(b *strings.Builder, runs []RunResult, totalMonths float64) {
	b.WriteString("---\n\n## Cost and timing\n\n")

	type modelTotals struct {
		requests, promptTokens, completionTokens, totalTokens, priceFound int
		costUSD                                                           float64
	}
	byModel := map[string]*modelTotals{}
	var totalCost float64
	var totalRequests, totalPriceFound int
	var totalDuration time.Duration

	for _, r := range runs {
		if !r.FinishedAt.IsZero() && !r.StartedAt.IsZero() {
			totalDuration += r.FinishedAt.Sub(r.StartedAt)
		}
		for _, u := range r.Usage {
			mt, ok := byModel[u.Model]
			if !ok {
				mt = &modelTotals{}
				byModel[u.Model] = mt
			}
			mt.requests += u.RequestCount
			mt.promptTokens += u.PromptTokens
			mt.completionTokens += u.CompletionTokens
			mt.totalTokens += u.TotalTokens
			mt.costUSD += u.EstimatedCostUSD
			mt.priceFound += u.PriceFoundCount
			totalCost += u.EstimatedCostUSD
			totalRequests += u.RequestCount
			totalPriceFound += u.PriceFoundCount
		}
	}

	if len(byModel) == 0 {
		b.WriteString("**No Costguard usage data captured.** Either the usage query failed (check `run`'s stderr ")
		b.WriteString("output for a WARNING line) or Costguard's usage_records table genuinely has no rows for this ")
		b.WriteString("run's agent/time window. Cost figures below are all zero and NOT meaningful until this is fixed.\n\n")
	} else if totalPriceFound < totalRequests {
		fmt.Fprintf(b, "**%d of %d requests had no Costguard price configured (price_found=false).** For those, ",
			totalRequests-totalPriceFound, totalRequests)
		b.WriteString("estimated_cost_usd defaults to 0 — that means **UNMEASURED, not confirmed free.** Local, ")
		b.WriteString("self-hosted models (Ollama) genuinely may have zero marginal API cost, but this tool cannot ")
		b.WriteString("tell the difference between \"actually free\" and \"Costguard has no price entry for this model\" ")
		b.WriteString("from usage_records alone — see the Price found column below per model. If the true per-token ")
		b.WriteString("cost matters for the go/no-go decision (e.g. this ever moves to a metered API), configure ")
		b.WriteString("pricing for these models in Costguard before trusting the total below.\n\n")
	}

	models := make([]string, 0, len(byModel))
	for m := range byModel {
		models = append(models, m)
	}
	sort.Strings(models)

	b.WriteString("| Model | Requests | Prompt tokens | Completion tokens | Total tokens | Cost (USD) | Price found |\n")
	b.WriteString("|---|---|---|---|---|---|---|\n")
	for _, m := range models {
		mt := byModel[m]
		fmt.Fprintf(b, "| %s | %d | %d | %d | %d | $%.4f | %d/%d |\n", m, mt.requests, mt.promptTokens, mt.completionTokens, mt.totalTokens, mt.costUSD, mt.priceFound, mt.requests)
	}
	fmt.Fprintf(b, "| **Total** | | | | | **$%.4f** | %d/%d |\n\n", totalCost, totalPriceFound, totalRequests)

	b.WriteString("**Embeddings are now included above** (as their own `nomic-embed-text` / `/v1/embeddings` row) — ")
	b.WriteString("wired into the write pipeline via storeExtractedTriples, one embedding per distinct source message ")
	b.WriteString("(see internal/api/pipeline.go's embedMessages). Earlier dry-run reports from before that was wired ")
	b.WriteString("in showed this table with no embeddings row at all; if you're comparing against one of those, the ")
	b.WriteString("totals are not directly comparable.\n\n")

	b.WriteString("**Voice transcription is now included above too** (as its own `whisper-1` / ")
	b.WriteString("`/v1/audio/transcriptions` row) — `run`'s Transcriber is wired into ImportWhatsApp ")
	b.WriteString("(internal/api/import_whatsapp.go), which transcribes every voice message via a local-file ")
	b.WriteString("AudioFetcher scoped to the export's own directory before it reaches triage/extraction (see ")
	b.WriteString("internal/api/voice_transcription.go). An escalation to OpenAI — low local confidence, or Arabic ")
	b.WriteString("regardless of confidence, see shouldEscalateTranscription — would show as a SEPARATE `whisper-1` ")
	b.WriteString("row if usage_records distinguishes provider by path/model the same way (check the raw usage rows, ")
	b.WriteString("not just this collapsed-by-model table, if escalation cost specifically matters). This deployment's ")
	b.WriteString("current `AUDIO_TRANSCRIPTION_PROVIDER=local` Costguard config means escalation calls may not ")
	b.WriteString("actually reach OpenAI regardless (see extraction.TranscribeOptions.ProviderHint's own doc ")
	b.WriteString("comment) — the cost row above reflects whatever Costguard actually did, not what §5 intends once ")
	b.WriteString("that's reconfigured. A voice message whose transcription fails entirely (both local and escalated) ")
	b.WriteString("is logged (see transcribeVoiceMessage) and left unprocessed/un-windowed — it contributes no ")
	b.WriteString("transcription cost but also never reaches extraction or embedding, same as before this was wired ")
	b.WriteString("in. Earlier dry-run reports from before voice transcription was wired in showed this table with ")
	b.WriteString("no `whisper-1` row at all; if you're comparing against one of those, the totals are not directly ")
	b.WriteString("comparable.\n\n")

	fmt.Fprintf(b, "- Wall-clock duration for this run: %s\n", totalDuration.Round(time.Second))

	if totalMonths > 0 {
		extrapolatedDuration := time.Duration(float64(totalDuration) * totalMonths).Round(time.Second)
		fmt.Fprintf(b, "- Extrapolated to %.1f months of history: **$%.2f**, **%s**\n\n", totalMonths, totalCost*totalMonths, extrapolatedDuration)
	} else {
		b.WriteString("- No `--total-months` given, so no extrapolated total is shown — multiply the cost/duration ")
		b.WriteString("above by however many months of real backlog exist, or re-run report with `--total-months`. ")
		b.WriteString("Compare the extrapolated total against whatever full-import cost estimate the proposal states ")
		b.WriteString("— that figure isn't available to this tool (the proposal document isn't checked into this repo).\n\n")
	}
}

func writeFailureClusters(b *strings.Builder, runs []RunResult) {
	b.WriteString("---\n\n## Failure clusters worth a dedicated look\n\n")
	b.WriteString("These are surfaced because they're the likely places a real problem would show up — not a ")
	b.WriteString("substitute for the random sample in `sample.md`, which is still the primary accuracy-review artifact.\n\n")

	items := flattenOutcomes(runs)

	b.WriteString("### Confidence outliers\n\n")
	if len(items) == 0 {
		b.WriteString("_(no extracted triples to analyze)_\n\n")
	} else {
		sorted := append([]sampleItem(nil), items...)
		sort.Slice(sorted, func(i, j int) bool { return sorted[i].Outcome.Triple.Confidence < sorted[j].Outcome.Triple.Confidence })

		var sum float64
		for _, it := range sorted {
			sum += it.Outcome.Triple.Confidence
		}
		mean := sum / float64(len(sorted))
		median := sorted[len(sorted)/2].Outcome.Triple.Confidence
		fmt.Fprintf(b, "n=%d, min=%.2f, max=%.2f, mean=%.2f, median=%.2f\n\n", len(sorted), sorted[0].Outcome.Triple.Confidence, sorted[len(sorted)-1].Outcome.Triple.Confidence, mean, median)

		writeOutlierTable(b, "Lowest confidence", sorted, false)
		writeOutlierTable(b, "Highest confidence", sorted, true)
	}

	b.WriteString("### Windows triage flagged as candidates that produced zero extracted triples\n\n")
	b.WriteString("A possible triage-to-extraction gap: triage saw something worth a closer look, but extraction ")
	b.WriteString("found nothing (a legitimate outcome per the extraction prompt's own \"[] if nothing extractable\" ")
	b.WriteString("instruction — not necessarily a bug, but worth eyeballing).\n\n")
	zeroCount := 0
	for _, r := range runs {
		if r.Import == nil {
			continue
		}
		for _, w := range r.Import.Windows {
			if w.IsCandidate && len(w.Outcomes) == 0 {
				zeroCount++
				fmt.Fprintf(b, "**%s, window %d:**\n\n%s\n", r.ExportPath, w.Index, windowContext(w.Messages))
			}
		}
	}
	if zeroCount == 0 {
		b.WriteString("_(none — every candidate window produced at least one triple)_\n\n")
	}

	b.WriteString("### Closed-vocabulary rejections\n\n")
	b.WriteString("Extraction output that ValidateTriples rejected — a predicate outside the closed vocabulary, a ")
	b.WriteString("bad object_type, or an out-of-range confidence. Captured verbatim from extraction's own rejection log.\n\n")
	var allRejections []string
	for _, r := range runs {
		allRejections = append(allRejections, r.RejectedTripleLogLines...)
	}
	if len(allRejections) == 0 {
		b.WriteString("_(none)_\n\n")
	} else {
		for _, line := range allRejections {
			fmt.Fprintf(b, "- %s\n", line)
		}
		b.WriteString("\n")
	}
}

func writeOutlierTable(b *strings.Builder, title string, sorted []sampleItem, highest bool) {
	fmt.Fprintf(b, "**%s (top %d):**\n\n", title, outlierCount)
	b.WriteString("| Confidence | Subject | Predicate | Object |\n|---|---|---|---|\n")

	n := outlierCount
	if n > len(sorted) {
		n = len(sorted)
	}
	for i := 0; i < n; i++ {
		var it sampleItem
		if highest {
			it = sorted[len(sorted)-1-i]
		} else {
			it = sorted[i]
		}
		t := it.Outcome.Triple
		fmt.Fprintf(b, "| %.2f | %s | %s | %s |\n", t.Confidence, t.Subject, t.Predicate, t.Object)
	}
	b.WriteString("\n")
}
